#!/usr/bin/env python
"""Build a small GitHub Pages-ready static blog for AI Morning Radar."""
from __future__ import annotations

import html
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
POSTS_DIR = ROOT / "dist" / "blog"
SITE_DIR = ROOT / "site"
SITE_POSTS = SITE_DIR / "posts"

LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
CODE_RE = re.compile(r"`([^`]+)`")
BOLD_RE = re.compile(r"\*\*([^*]+)\*\*")


def inline_md(s: str) -> str:
    s = html.escape(s)
    s = LINK_RE.sub(lambda m: f'<a href="{html.escape(m.group(2), quote=True)}">{html.escape(m.group(1))}</a>', s)
    s = CODE_RE.sub(lambda m: f'<code>{html.escape(m.group(1))}</code>', s)
    s = BOLD_RE.sub(lambda m: f'<strong>{html.escape(m.group(1))}</strong>', s)
    return s


def render_markdown(md: str) -> str:
    body: list[str] = []
    in_ul = False
    in_ol = False

    def close_lists() -> None:
        nonlocal in_ul, in_ol
        if in_ul:
            body.append("</ul>")
            in_ul = False
        if in_ol:
            body.append("</ol>")
            in_ol = False

    for raw in md.splitlines():
        line = raw.rstrip()
        if not line:
            close_lists()
            continue
        if line == "---":
            close_lists()
            body.append("<hr>")
        elif line.startswith("# "):
            close_lists()
            body.append(f"<h1>{inline_md(line[2:].strip())}</h1>")
        elif line.startswith("## "):
            close_lists()
            body.append(f"<h2>{inline_md(line[3:].strip())}</h2>")
        elif line.startswith("### "):
            close_lists()
            body.append(f"<h3>{inline_md(line[4:].strip())}</h3>")
        elif line.startswith("> "):
            close_lists()
            body.append(f"<blockquote>{inline_md(line[2:].strip())}</blockquote>")
        elif re.match(r"^\d+\.\s+", line):
            if not in_ol:
                close_lists()
                body.append("<ol>")
                in_ol = True
            item = re.sub(r"^\d+\.\s+", "", line)
            body.append(f"<li>{inline_md(item)}</li>")
        elif line.lstrip().startswith("- "):
            if not in_ul:
                close_lists()
                body.append("<ul>")
                in_ul = True
            body.append(f"<li>{inline_md(line.lstrip()[2:].strip())}</li>")
        else:
            close_lists()
            body.append(f"<p>{inline_md(line.strip())}</p>")
    close_lists()
    return "\n".join(body)


def page(title: str, content: str, *, description: str = "AI Morning Radar") -> str:
    return f"""<!doctype html>
<html lang="ko">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="{html.escape(description, quote=True)}">
  <title>{html.escape(title)}</title>
  <link rel="stylesheet" href="/assets/style.css">
</head>
<body>
  <header class="site-header">
    <a class="brand" href="/">AI Morning Radar</a>
    <span class="tagline">바쁜 사람을 위한 AI 뉴스 브리핑</span>
  </header>
  <main class="container">
    {content}
  </main>
  <footer class="site-footer">Generated by newsNblog · Original sources linked in each item</footer>
</body>
</html>
"""


def main() -> int:
    SITE_POSTS.mkdir(parents=True, exist_ok=True)
    (SITE_DIR / "assets").mkdir(parents=True, exist_ok=True)

    posts = []
    for md_path in sorted(POSTS_DIR.glob("*.md"), reverse=True):
        date = md_path.stem
        md = md_path.read_text(encoding="utf-8")
        title = md.splitlines()[0].lstrip("# ").strip() if md.splitlines() else date
        content = f'<article class="post">\n{render_markdown(md)}\n</article>'
        out = SITE_POSTS / f"{date}.html"
        out.write_text(page(title, content, description=title), encoding="utf-8")
        posts.append((date, title, f"/posts/{date}.html"))

    items = "\n".join(
        f'<li><a href="{href}">{html.escape(title)}</a><time>{date}</time></li>'
        for date, title, href in posts
    ) or "<li>아직 게시물이 없습니다.</li>"
    index_content = f"""
<section class="hero">
  <p class="eyebrow">Daily AI Briefing</p>
  <h1>AI Morning Radar</h1>
  <p>AI 뉴스, X/Threads 트렌드, GeekNews 개발자 관점, 실제 UseCase를 아침에 빠르게 읽는 브리핑입니다.</p>
</section>
<section class="post-list">
  <h2>브리핑 아카이브</h2>
  <ul>{items}</ul>
</section>
"""
    (SITE_DIR / "index.html").write_text(page("AI Morning Radar", index_content), encoding="utf-8")

    css = """
:root { color-scheme: light; --bg:#f5f7fb; --card:#fff; --text:#172033; --muted:#667085; --link:#2563eb; --line:#e7ebf3; }
* { box-sizing: border-box; }
body { margin:0; background:var(--bg); color:var(--text); font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Noto Sans KR",Arial,sans-serif; line-height:1.68; }
a { color:var(--link); text-decoration:none; font-weight:650; }
a:hover { text-decoration:underline; }
.site-header { max-width:920px; margin:0 auto; padding:28px 18px 8px; display:flex; gap:14px; align-items:baseline; }
.brand { color:#101828; font-size:20px; font-weight:800; }
.tagline { color:var(--muted); font-size:14px; }
.container { max-width:920px; margin:0 auto; padding:18px 18px 48px; }
.hero, .post, .post-list { background:var(--card); border:1px solid var(--line); border-radius:22px; padding:32px; box-shadow:0 10px 30px rgba(20,34,66,.06); }
.hero h1, .post h1 { margin-top:0; font-size:34px; line-height:1.2; }
.eyebrow { color:#5b6b86; font-size:13px; letter-spacing:.08em; text-transform:uppercase; font-weight:700; }
.post h2 { font-size:23px; margin:38px 0 14px; padding-top:22px; border-top:1px solid #edf0f6; }
.post h3 { font-size:18px; margin:28px 0 10px; }
.post ul, .post ol { padding-left:24px; }
.post li { margin:7px 0; }
blockquote { margin:16px 0 24px; padding:16px 18px; background:#eef6ff; border-left:4px solid #3b82f6; border-radius:12px; color:#153459; font-weight:650; }
hr { border:0; height:1px; background:#edf0f6; margin:28px 0; }
code { background:#f2f4f7; border-radius:6px; padding:1px 5px; font-size:.92em; }
.post-list { margin-top:18px; }
.post-list ul { list-style:none; padding:0; margin:0; }
.post-list li { display:flex; justify-content:space-between; gap:16px; padding:14px 0; border-top:1px solid #edf0f6; }
.post-list time { color:var(--muted); white-space:nowrap; }
.site-footer { max-width:920px; margin:0 auto; padding:0 18px 36px; color:var(--muted); font-size:13px; text-align:center; }
@media (max-width:640px) { .site-header { display:block; } .hero, .post, .post-list { padding:22px; border-radius:16px; } .hero h1, .post h1 { font-size:28px; } .post-list li { display:block; } }
""".strip() + "\n"
    (SITE_DIR / "assets" / "style.css").write_text(css, encoding="utf-8")

    print(f"built {SITE_DIR}")
    for path in [SITE_DIR / "index.html", *(SITE_POSTS.glob("*.html")), SITE_DIR / "assets" / "style.css"]:
        print(path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
