#!/usr/bin/env python
"""Daily pipeline orchestrator — processes ALL configured tracks (ai, ax, …).

Flow per track:
  1. (research)   codex exec with track's prompt -> briefings/{track}/{date}.md
                  + track's published_csv update   (skip with --skip-research)
  2. (render)     scripts/render_briefing.py --track {key} {date}
  3. (email)      scripts/send_email.py --track {key} {date}
Then, once for all done tracks:
  4. (site)       scripts/build_site.py
  5. (publish)    git commit + push (briefings + published csvs)
  6. (log)        append per-track delivery logs + commit/push

Resilience: a failing track (research/verify/render/email) is caught and logged;
the remaining tracks continue unaffected.

Usage:
  python scripts/daily_run.py                 # full pipeline, all tracks, today
  python scripts/daily_run.py --date 2026-06-09
  python scripts/daily_run.py --tracks ai     # single track
  python scripts/daily_run.py --skip-research # briefings already written
  python scripts/daily_run.py --no-send --no-push   # local dry test
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

# Scheduled-task consoles on Windows default to cp949, which crashes on any
# non-cp949 char (e.g. em-dash) the moment we print. Force utf-8 so logging a
# command or the prompt never aborts the pipeline.
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass

ROOT = Path(__file__).resolve().parents[1]
PY = sys.executable
sys.path.insert(0, str(ROOT / "scripts"))
import tracks


def run(cmd: list[str], **kw) -> subprocess.CompletedProcess:
    # Don't dump multi-KB prompt bodies into the log; show only short args.
    shown = [c if len(str(c)) <= 120 else f"<{len(str(c))} chars>" for c in cmd]
    print(f"$ {' '.join(str(c) for c in shown)}", flush=True)
    # text=True decodes child output with the cp949 locale on Windows, which
    # crashes the reader thread on utf-8/Korean bytes. Force utf-8 here too.
    kw.setdefault("encoding", "utf-8")
    kw.setdefault("errors", "replace")
    return subprocess.run(cmd, cwd=str(ROOT), text=True, **kw)


def already_sent(track, date: str) -> bool:
    log = ROOT / track.delivery_log
    if not log.exists():
        return False
    import csv
    with log.open(encoding="utf-8", newline="") as f:
        return any(r.get("date") == date and r.get("status") == "sent" for r in csv.DictReader(f))


def published_keys(track) -> str:
    """Return a compact list of already-published titles for the prompt context."""
    csv_path = ROOT / track.published_csv
    if not csv_path.exists():
        return "(none)"
    import csv as _csv
    lines = []
    with csv_path.open(encoding="utf-8", newline="") as f:
        for r in _csv.DictReader(f):
            lines.append(f"- {r.get('first_published_date','')} | {r.get('title','')} | {r.get('url','')}")
    # Only the most recent ~40 to keep the prompt bounded.
    return "\n".join(lines[-40:]) if lines else "(none)"


def find_codex() -> str:
    for c in (
        os.environ.get("CODEX_EXE"),
        shutil.which("codex"),
        shutil.which("codex.cmd"),
        str(Path.home() / "AppData" / "Roaming" / "npm" / "codex.cmd"),
        str(Path.home() / ".local" / "bin" / "codex"),
    ):
        if c and Path(c).exists():
            return c
    return "codex"


def find_claude() -> str:
    # Research runs on Codex now; translation still runs on Claude (the user finds
    # Codex translation quality insufficient).
    for c in (
        os.environ.get("CLAUDE_EXE"),
        shutil.which("claude"),
        shutil.which("claude.cmd"),
        str(Path.home() / ".local" / "bin" / "claude.exe"),
        str(Path.home() / ".local" / "bin" / "claude"),
        str(Path.home() / "AppData" / "Roaming" / "npm" / "claude.cmd"),
    ):
        if c and Path(c).exists():
            return c
    return "claude"


def translate(track, date: str) -> None:
    """Write a long-form Korean expansion of this post's FOREIGN-language sources
    to translations/{key}/{date}.md, generated by Claude.

    Never raises: translation is best-effort and runs AFTER the email is sent, so
    a failure here must not block delivery. Produces no file when the post has no
    foreign-language sources (so build_site shows no button / no page).
    """
    briefing = ROOT / track.paths(date)["briefing"]
    out = ROOT / track.translated_md(date)
    prompt = (
        "너는 한국어 뉴스 블로그의 번역 도우미다.\n"
        f"먼저 이 브리핑 파일을 읽어라: {briefing.as_posix()}\n\n"
        "그 안에서 '소스(원문 기사)가 한국어가 아닌 외국어'인 항목을 모두 골라라.\n"
        "각 항목에 대해, 링크된 원문 기사를 WebFetch로 실제로 읽고, 그 기사 내용을 한국어로 "
        "'길게' 풀어써라(브리핑의 3줄 요약보다 훨씬 자세히: 핵심 사실·맥락·숫자·인용·함의). "
        "요약이 아니라 원문을 한국어로 충실히 옮기고 설명하는 글이다.\n\n"
        "출력 형식(마크다운):\n"
        f"- 첫 줄: '# {date} {track.name} — 원문 한국어 해설'\n"
        "- 그 아래 인용구('>') 한 줄 안내문.\n"
        "- 항목마다 '## [원문 제목 한국어](원문 URL)' 헤딩 + 여러 문단. 필요하면 ###·목록 사용.\n\n"
        "규칙(중요):\n"
        "- 한국어 소스(.kr·국내 매체·GeekNews 등 한국어 원문) 항목은 제외한다.\n"
        "- 원문에 없는 사실을 지어내지 마라. 페이월·차단으로 본문을 못 읽으면 그 항목에 "
        "'(원문 접근 제한: …)'이라 적고 브리핑에 이미 있는 정보 범위에서만 정리한다.\n"
        "- 숫자·고유명사·인용은 원문 그대로. 추정·과장 금지.\n"
        "- 모든 링크 URL은 반드시 원문 기사의 http(s) 주소만 사용하라. javascript:·data: 등 다른 스킴 금지.\n"
        f"- 결과를 '{out.as_posix()}' 파일에 써라(기존 내용은 덮어쓴다).\n"
        "- 외국어 소스 항목이 하나도 없으면 파일에 정확히 'NO_FOREIGN_SOURCES' 한 줄만 써라.\n"
        "끝나면 'TRANSLATED_WRITTEN' 한 줄을 출력하라.\n"
    )
    cmd = [find_claude(), "-p", prompt, "--permission-mode", "bypassPermissions",
           "--add-dir", str(ROOT)]
    # Headless Claude gets a fresh session every run; a huge throttle disables the
    # global insight-harvest Stop hook for this child only.
    env = {**os.environ, "CLAUDE_INSIGHT_THROTTLE_MIN": "1000000"}
    # Guard the ENTIRE body: no failure (subprocess launch/timeout, mkdir, decode,
    # unlink, write) may propagate. If it did, run_track would raise and the track
    # would be dropped from `done` AFTER its email already went out — re-sending a
    # duplicate on the next run. Translation is strictly best-effort.
    try:
        out.parent.mkdir(parents=True, exist_ok=True)
        res = run(cmd, capture_output=True, timeout=1800, env=env)
        if res.stdout:
            print(res.stdout[-1500:])
        if res.stderr:
            print(res.stderr[-800:], file=sys.stderr)
        txt = out.read_text(encoding="utf-8", errors="replace").strip() if out.exists() else ""
        if res.returncode != 0 or not txt or txt == "NO_FOREIGN_SOURCES":
            if out.exists():
                out.unlink()  # no broken button/page
            why = (f"claude exit {res.returncode}" if res.returncode != 0
                   else "no foreign sources" if txt == "NO_FOREIGN_SOURCES" else "empty output")
            print(f"[{track.key}] no translation page for {date} ({why}).")
            return
        cleaned = "\n".join(l for l in txt.splitlines() if l.strip() != "TRANSLATED_WRITTEN").rstrip() + "\n"
        out.write_text(cleaned, encoding="utf-8")
        print(f"[{track.key}] translation page written: {out}")
    except Exception as e:  # best-effort: never block delivery
        print(f"[{track.key}] translate skipped/failed for {date} ({e})", file=sys.stderr)


def research(track, date: str) -> None:
    prompt = (ROOT / track.prompt).read_text(encoding="utf-8").replace("{DATE}", date)
    prompt += f"\n\n## 이미 발행된 항목 (반복 금지)\n{published_keys(track)}\n"
    prompt += f"\n오늘 날짜: {date}\n"
    # Headless Codex run — the non-interactive analogue of `claude -p`.
    #   exec                                       : non-interactive subcommand.
    #   --dangerously-bypass-approvals-and-sandbox : unattended; Windows has no
    #       OS-level sandbox to confine writes, so this is the practical
    #       equivalent of claude's --permission-mode bypassPermissions.
    #   --skip-git-repo-check                      : don't refuse to run in/around git.
    #   -c tools.web_search=true                   : enable live web search — the
    #       whole point of a news briefing; OFF by default in `codex exec`
    #       (the top-level `--search` flag is not accepted by the exec subcommand).
    #   -C ROOT                                    : working root (writes land here).
    #   --add-dir <dir> (AX track)                 : vault access for the research lens.
    #   -  (final arg)                             : read the prompt from STDIN.
    # The prompt is multi-KB; passing it as an argv element blows cmd.exe's
    # ~8191-char command-line limit through the npm `codex.cmd` batch shim
    # ("명령줄이 너무 깁니다"). stdin has no such limit, so we pipe it instead.
    cmd = [find_codex(), "exec", "--dangerously-bypass-approvals-and-sandbox",
           "--skip-git-repo-check", "-c", "tools.web_search=true", "-C", str(ROOT)]
    for d in track.add_dirs:
        cmd += ["--add-dir", d]
    cmd += ["-"]
    res = run(cmd, capture_output=True, timeout=1500, input=prompt)
    if res.stdout:
        print(res.stdout[-2000:])
    if res.stderr:
        print(res.stderr[-1000:], file=sys.stderr)
    if res.returncode != 0:
        raise SystemExit(f"research step failed for track {track.key} (codex exit {res.returncode})")


def verify_briefing(track, date: str) -> Path:
    path = ROOT / track.paths(date)["briefing"]
    if not path.exists():
        raise SystemExit(f"ERROR: {path} was not produced; aborting track {track.key}.")
    text = path.read_text(encoding="utf-8")
    if len(text) < 800 or "세 줄 요약" not in text:
        raise SystemExit(f"ERROR: {path} looks incomplete ({len(text)} bytes); aborting track {track.key}.")
    return path


def git(*args: str) -> subprocess.CompletedProcess:
    return run(["git", *args], capture_output=True)


def head_sha() -> str:
    r = git("rev-parse", "--short", "HEAD")
    return (r.stdout or "").strip()


def run_track(track, date: str, *, skip_research: bool, no_send: bool) -> None:
    """Run research/verify/render/email for one track; raises SystemExit on failure."""
    if not skip_research:
        research(track, date)
    verify_briefing(track, date)
    if run([PY, "scripts/render_briefing.py", "--track", track.key, date]).returncode != 0:
        raise SystemExit(f"render step failed for track {track.key}")
    if not no_send:
        if run([PY, "scripts/send_email.py", "--track", track.key, date]).returncode != 0:
            raise SystemExit(f"email step failed for track {track.key}")
        # Best-effort Korean translation page for foreign-sourced items. Runs after
        # the email (never blocks/delays delivery) and never raises. Skipped under
        # --no-send so a "local dry test" stays fast (no ~30-min Claude subprocess).
        translate(track, date)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--date", default=datetime.now().strftime("%Y-%m-%d"))
    ap.add_argument("--tracks", default=",".join(tracks.ORDER),
                    help="comma-separated track keys to run")
    ap.add_argument("--skip-research", action="store_true")
    ap.add_argument("--no-send", action="store_true")
    ap.add_argument("--no-push", action="store_true")
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()
    date = args.date
    keys = [k.strip() for k in args.tracks.split(",") if k.strip()]

    done = []   # tracks that produced publishable content this run
    for key in keys:
        try:
            track = tracks.get_track(key)
            if already_sent(track, date) and not args.force:
                print(f"[{key}] {date} already sent; skipping.")
                continue
            run_track(track, date, skip_research=args.skip_research, no_send=args.no_send)
            done.append(track)
        except SystemExit as e:
            print(f"[{key}] FAILED: {e}", file=sys.stderr)
        except Exception as e:
            print(f"[{key}] FAILED: {e}", file=sys.stderr)

    if not done:
        print("No track produced content; nothing to publish.")
        return 0

    if run([PY, "scripts/build_site.py"]).returncode != 0:
        raise SystemExit("build_site step failed")

    if not args.no_push:
        add_paths = []
        for t in done:
            add_paths += [t.briefings_dir + f"/{date}.md", t.published_csv]
            tmd = t.translated_md(date)
            if (ROOT / tmd).exists():
                add_paths.append(str(tmd))
            else:
                # Translation removed this run (no foreign sources / failure). Stage
                # the deletion so a previously committed page can't linger on the
                # deployed site. --ignore-unmatch makes it a no-op if never tracked.
                git("rm", "--ignore-unmatch", "-q", str(tmd))
        git("add", *add_paths)
        c = git("commit", "-m", f"Publish {date} [{', '.join(t.key for t in done)}]")
        if c.returncode != 0:
            raise SystemExit(f"publish commit failed: {(c.stderr or c.stdout or '').strip()[:300]}")
        pu = git("push", "origin", "main")
        if pu.returncode != 0:
            raise SystemExit(f"publish push failed: {(pu.stderr or pu.stdout or '').strip()[:300]}")
    sha = head_sha()

    completed = datetime.now().isoformat(timespec="seconds")
    status = "rendered" if (args.no_send or args.no_push) else "sent"
    for t in done:
        pages_url = t.pages_url(date)
        with (ROOT / t.delivery_log).open("a", encoding="utf-8", newline="") as f:
            f.write(f"{date},{status},,{sha},{pages_url},{completed},codex-driven pipeline\n")
    if not args.no_push:
        git("add", *[t.delivery_log for t in done])
        c = git("commit", "-m", f"Log {date} delivery [{', '.join(t.key for t in done)}]")
        if c.returncode != 0:
            raise SystemExit(f"log commit failed: {(c.stderr or c.stdout or '').strip()[:300]}")
        pu = git("push", "origin", "main")
        if pu.returncode != 0:
            raise SystemExit(f"log push failed: {(pu.stderr or pu.stdout or '').strip()[:300]}")

    for t in done:
        print(f"DONE {date} [{t.key}]: status={status} pages={t.pages_url(date)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
